// 'use client'
import { Geist, Geist_Mono, Noto_Serif, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
// import { Providers } from "@/redux/provider";
import { ErrorBoundary } from "node_modules/next/dist/client/components/error-boundary";
import { Toaster } from 'react-hot-toast';

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans-src",
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins-src",
  display: "swap"
});
const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif-src",
  display: "swap"
});

export const metadata = {
  title: "AliumPro",
  icons: {
  icon: "/logo.ico",          // create favicon.ico from your logo
  shortcut: "/logo-32x32.png",
  apple: "/apple-touch-icon.png",
},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${poppins.variable} ${notoSerif.variable} antialiased`}
      >
        {/* <ErrorBoundary FallbackComponent={Error}> */}
          
            {children}
          
        {/* </ErrorBoundary> */}

        <Toaster />
      </body>
    </html>
  );
}
