
import { Noto_Serif, Open_Sans, Poppins, Nunito, Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Providers } from "@/redux/provider";



const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans-src",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-src",
});



const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins-src",
  display: "swap"
});
const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-nunito-src",
  display: "swap"
});
const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif-src",
  display: "swap"
});

export const metadata = {
  title: "AliumPro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${poppins.variable} ${notoSerif.variable} ${nunito.variable} ${inter.variable} antialiased  bg-background text-foreground min-h-screen`}
      >

        <Providers>
          <div className=" absolute  inset-x-0 top-0 z-50">
            <Header />
          </div>
          
            <main className="">{children}</main>
          
          <Footer />
        </Providers>


      </body>
    </html>
  );
}
